# Generated by Django 3.2.10 on 2022-03-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('fromCity', models.CharField(max_length=20)),
                ('toCity', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=30)),
                ('numbers', models.SmallIntegerField()),
                ('type', models.SmallIntegerField()),
                ('initiator', models.CharField(max_length=20)),
                ('state', models.SmallIntegerField()),
            ],
        ),
    ]
