# Generated by Django 3.2.10 on 2022-03-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='discussion',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='joinTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=30)),
            ],
        ),
    ]
