# Generated by Django 3.2.10 on 2022-03-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_discussion_jointeam_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='joinTeam',
        ),
    ]
