# Generated by Django 3.2.10 on 2022-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_jointeam'),
    ]

    operations = [
        migrations.CreateModel(
            name='joinTeam',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=30)),
            ],
        ),
    ]
