# Generated by Django 3.2.10 on 2022-03-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_jointeam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='events',
        ),
    ]
