# Generated by Django 3.2.10 on 2022-03-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('fromCity', models.CharField(max_length=20)),
                ('toCity', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=30)),
                ('numbers', models.SmallIntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('departTime', models.DateTimeField()),
                ('type', models.SmallIntegerField()),
                ('content', models.TextField()),
                ('initiator', models.CharField(max_length=20)),
                ('initiatorId', models.SmallIntegerField()),
                ('createTime', models.DateTimeField()),
                ('modifyTime', models.DateTimeField()),
                ('relesseTime', models.DateTimeField()),
                ('state', models.SmallIntegerField()),
            ],
        ),
    ]
