# Generated by Django 3.2.10 on 2022-03-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='discussion',
        ),
        migrations.DeleteModel(
            name='joinTeam',
        ),
        migrations.DeleteModel(
            name='player',
        ),
    ]
