# Generated by Django 3.2.10 on 2022-03-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20220307_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='discussion',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('eventsId', models.IntegerField()),
                ('playerId', models.IntegerField()),
                ('playerName', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=200)),
                ('subTime', models.DateTimeField()),
                ('replyWho', models.IntegerField()),
                ('replyMessageId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='joinTeam',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('eventsId', models.IntegerField()),
                ('playerId', models.IntegerField()),
                ('playerName', models.CharField(max_length=30)),
                ('isInit', models.BooleanField()),
                ('applicationTime', models.DateTimeField()),
                ('auditTime', models.DateTimeField()),
                ('state', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False)),
                ('playerName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('createTime', models.DateTimeField()),
            ],
        ),
    ]
