# Generated by Django 3.2.10 on 2022-03-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_player_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointeam',
            name='eventsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
