# Generated by Django 3.2.10 on 2022-03-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_jointeam_eventsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='eventsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.player'),
        ),
        migrations.AlterField(
            model_name='jointeam',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.player'),
        ),
    ]
