# Generated by Django 3.2.10 on 2022-03-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20220319_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='eventsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.player'),
        ),
        migrations.AlterField(
            model_name='jointeam',
            name='eventsId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.events'),
        ),
        migrations.AlterField(
            model_name='jointeam',
            name='playerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.player'),
        ),
    ]
