# Generated by Django 3.2.10 on 2022-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20220319_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='relesseTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='jointeam',
            name='auditTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='jointeam',
            name='isInit',
            field=models.BooleanField(blank=True),
        ),
    ]
