# Generated by Django 3.2.10 on 2022-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220319_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': '玩家'},
        ),
        migrations.AlterField(
            model_name='player',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
