# Generated by Django 3.2.10 on 2022-03-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20220319_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
    ]
