# Generated by Django 3.2.10 on 2022-03-20 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_player_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='initiatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.player'),
        ),
        migrations.AlterField(
            model_name='events',
            name='modifyTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
