# Generated by Django 3.2.10 on 2022-03-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20220320_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(help_text='活动名称', max_length=50),
        ),
    ]
