# Generated by Django 3.2.10 on 2022-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_events_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': '玩家'},
        ),
        migrations.AlterField(
            model_name='events',
            name='content',
            field=models.TextField(verbose_name='活动内容'),
        ),
        migrations.AlterField(
            model_name='events',
            name='departTime',
            field=models.DateTimeField(verbose_name='集合时间'),
        ),
        migrations.AlterField(
            model_name='events',
            name='destination',
            field=models.CharField(max_length=30, verbose_name='目的地'),
        ),
        migrations.AlterField(
            model_name='events',
            name='endDate',
            field=models.DateField(verbose_name='至'),
        ),
        migrations.AlterField(
            model_name='events',
            name='fromCity',
            field=models.CharField(max_length=20, verbose_name='出发地'),
        ),
        migrations.AlterField(
            model_name='events',
            name='numbers',
            field=models.SmallIntegerField(verbose_name='人数限制'),
        ),
        migrations.AlterField(
            model_name='events',
            name='startDate',
            field=models.DateField(verbose_name='行程'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=50, verbose_name='活动名称'),
        ),
        migrations.AlterField(
            model_name='events',
            name='toCity',
            field=models.CharField(max_length=20, verbose_name='到达'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.SmallIntegerField(verbose_name='活动类型'),
        ),
    ]
