# Generated by Django 3.2.10 on 2022-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20220320_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name_plural': '活动组队'},
        ),
        migrations.AlterField(
            model_name='events',
            name='relesseTime',
            field=models.DateTimeField(blank=True, verbose_name='发布时间'),
        ),
    ]
