# Generated by Django 3.2.10 on 2022-03-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20220320_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name_plural': '讨论组'},
        ),
        migrations.AlterModelOptions(
            name='jointeam',
            options={'verbose_name_plural': '活动组队'},
        ),
    ]
