# Generated by Django 3.2.10 on 2022-03-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_events_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.SmallIntegerField(choices=[('TK', '徒步'), ('CB', '登山'), ('TR', '越野跑'), ('RT', '溯溪')], verbose_name='活动类型'),
        ),
    ]
