# Generated by Django 3.2.10 on 2022-03-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.SmallIntegerField(choices=[('1', '徒步'), ('2', '登山'), ('3', '越野跑'), ('4', '溯溪')], verbose_name='活动类型'),
        ),
    ]
