# Generated by Django 3.2.10 on 2022-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_events_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': '活动管理'},
        ),
        migrations.AddField(
            model_name='events',
            name='artPhoto',
            field=models.ImageField(blank=True, upload_to='media/artphoto/', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='events',
            name='state',
            field=models.SmallIntegerField(default=0),
        ),
    ]
