# Generated by Django 3.2.10 on 2022-03-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20220327_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='state',
            new_name='status',
        ),
    ]
