# Generated by Django 3.2.10 on 2022-07-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_events_relessetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='artPhoto',
            field=models.ImageField(blank=True, upload_to='artphoto/', verbose_name='活动图片'),
        ),
        migrations.AlterField(
            model_name='events',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '徒步'), (2, '登山'), (3, '越野跑'), (4, '溯溪')], verbose_name='活动类型'),
        ),
    ]
