# Generated by Django 3.2.10 on 2022-08-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20220726_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='message',
            field=models.CharField(max_length=200, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='messageId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='留言ID'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='playerName',
            field=models.CharField(max_length=30, verbose_name='留言者'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='replyMessageId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='replyWho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='subTime',
            field=models.DateTimeField(verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='events',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='jointeam',
            name='auditTime',
            field=models.DateTimeField(),
        ),
    ]
